#!/usr/bin/env bash
#
# vendor-zlib.sh
# Downloads and vendors zlib source into Sources/Compression/CZlib
# so it can be built as a Swift-PM C target.
#
# Usage:
#   ./Scripts/vendor-zlib.sh          # uses default version
#   ./Scripts/vendor-zlib.sh 1.3.1    # specify version
#
set -euo pipefail

ZLIB_VERSION="${1:-1.3.1}"
ZLIB_URL="https://github.com/madler/zlib/releases/download/v${ZLIB_VERSION}/zlib-${ZLIB_VERSION}.tar.gz"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
CZLIB_DIR="${PROJECT_ROOT}/Sources/Compression/CZlib"
WORK_DIR="$(mktemp -d)"

cleanup() {
    rm -rf "${WORK_DIR}"
}
trap cleanup EXIT

echo "==> Vendoring zlib ${ZLIB_VERSION}"
echo "    URL: ${ZLIB_URL}"
echo "    Destination: ${CZLIB_DIR}"

# ---------------------------------------------------------------------------
# 1. Download & extract
# ---------------------------------------------------------------------------
echo "==> Downloading zlib ${ZLIB_VERSION}..."
curl -fsSL "${ZLIB_URL}" -o "${WORK_DIR}/zlib.tar.gz"

echo "==> Extracting..."
tar xzf "${WORK_DIR}/zlib.tar.gz" -C "${WORK_DIR}"

ZLIB_SRC="${WORK_DIR}/zlib-${ZLIB_VERSION}"

if [[ ! -d "${ZLIB_SRC}" ]]; then
    echo "Error: Expected source directory ${ZLIB_SRC} not found." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# 2. Prepare destination
# ---------------------------------------------------------------------------
echo "==> Preparing ${CZLIB_DIR}..."
rm -rf "${CZLIB_DIR}"
mkdir -p "${CZLIB_DIR}/include"
mkdir -p "${CZLIB_DIR}/src"

# ---------------------------------------------------------------------------
# 3. Copy source files
# ---------------------------------------------------------------------------
# Core C sources required to build zlib as a static library.
# The gz*.c files (gzip FILE* I/O) are intentionally excluded because they
# rely on POSIX symbols (read/write/close/lseek) that conflict with Swift's
# Clang-module isolation.
ZLIB_C_FILES=(
    adler32.c
    compress.c
    crc32.c
    deflate.c
    infback.c
    inffast.c
    inflate.c
    inftrees.c
    trees.c
    uncompr.c
    zutil.c
)

echo "==> Copying source files..."
for f in "${ZLIB_C_FILES[@]}"; do
    cp "${ZLIB_SRC}/${f}" "${CZLIB_DIR}/src/${f}"
done

# Internal headers needed by the C files (kept alongside sources)
ZLIB_INTERNAL_HEADERS=(
    crc32.h
    deflate.h
    gzguts.h
    inffast.h
    inffixed.h
    inflate.h
    inftrees.h
    trees.h
    zutil.h
)

for h in "${ZLIB_INTERNAL_HEADERS[@]}"; do
    if [[ -f "${ZLIB_SRC}/${h}" ]]; then
        cp "${ZLIB_SRC}/${h}" "${CZLIB_DIR}/src/${h}"
    fi
done

# ---------------------------------------------------------------------------
# 4. Copy public headers
# ---------------------------------------------------------------------------
echo "==> Copying public headers..."
cp "${ZLIB_SRC}/zlib.h"  "${CZLIB_DIR}/include/zlib.h"
cp "${ZLIB_SRC}/zconf.h" "${CZLIB_DIR}/include/zconf.h"

# ---------------------------------------------------------------------------
# 4b. Symbol renaming — avoid clashes with system / dylib zlib
# ---------------------------------------------------------------------------
# We create czlib_rename.h which #define-renames every public zlib symbol to
# a czlib_* equivalent.  We then append a single #include of that header to
# the vendored zconf.h.  Because zconf.h is pulled in by zlib.h, which is
# pulled in (directly or via zutil.h) by every C translation unit we compile,
# the renames are injected automatically: the resulting .o files emit czlib_*
# symbols instead of the stock zlib names.  Swift callers see the same names
# because the CZlib module header chain includes zconf.h too.
echo "==> Creating czlib_rename.h..."
cat > "${CZLIB_DIR}/include/czlib_rename.h" <<'RENAME'
/*
 * czlib_rename.h
 * Renames all public zlib symbols to CZlib_* to avoid clashing with any
 * system or dylib zlib present at link time.
 *
 * AUTO-GENERATED by vendor-zlib.sh — do not edit by hand.
 */
#ifndef CZLIB_RENAME_H
#define CZLIB_RENAME_H

#define deflate                CZlib_deflate
#define deflateEnd             CZlib_deflateEnd
#define deflateInit_           CZlib_deflateInit_
#define deflateInit2_          CZlib_deflateInit2_
#define deflateSetDictionary   CZlib_deflateSetDictionary
#define deflateGetDictionary   CZlib_deflateGetDictionary
#define deflateSetHeader       CZlib_deflateSetHeader
#define deflatePrime           CZlib_deflatePrime
#define deflateTune            CZlib_deflateTune
#define deflatePending         CZlib_deflatePending
#define deflateParams          CZlib_deflateParams
#define deflateReset           CZlib_deflateReset
#define deflateResetKeep       CZlib_deflateResetKeep
#define deflateBound           CZlib_deflateBound
#define deflateCopy            CZlib_deflateCopy

#define inflate                CZlib_inflate
#define inflateEnd             CZlib_inflateEnd
#define inflateInit_           CZlib_inflateInit_
#define inflateInit2_          CZlib_inflateInit2_
#define inflateSetDictionary   CZlib_inflateSetDictionary
#define inflateGetDictionary   CZlib_inflateGetDictionary
#define inflateSync            CZlib_inflateSync
#define inflateSyncPoint       CZlib_inflateSyncPoint
#define inflateCopy            CZlib_inflateCopy
#define inflateReset           CZlib_inflateReset
#define inflateReset2          CZlib_inflateReset2
#define inflateResetKeep       CZlib_inflateResetKeep
#define inflatePrime           CZlib_inflatePrime
#define inflateMark            CZlib_inflateMark
#define inflateBack            CZlib_inflateBack
#define inflateBackInit_       CZlib_inflateBackInit_
#define inflateBackEnd         CZlib_inflateBackEnd
#define inflateUndermine       CZlib_inflateUndermine
#define inflateValidate        CZlib_inflateValidate
#define inflateCodesUsed       CZlib_inflateCodesUsed

#define compress               CZlib_compress
#define compress2              CZlib_compress2
#define compressBound          CZlib_compressBound
#define uncompress             CZlib_uncompress
#define uncompress2            CZlib_uncompress2

#define adler32                CZlib_adler32
#define adler32_z              CZlib_adler32_z
#define adler32_combine        CZlib_adler32_combine
#define adler32_combine64      CZlib_adler32_combine64

#define crc32                  CZlib_crc32
#define crc32_z                CZlib_crc32_z
#define crc32_combine          CZlib_crc32_combine
#define crc32_combine64        CZlib_crc32_combine64
#define crc32_combine_gen      CZlib_crc32_combine_gen
#define crc32_combine_gen64    CZlib_crc32_combine_gen64
#define crc32_combine_op       CZlib_crc32_combine_op
#define get_crc_table          CZlib_get_crc_table

#define zError                 CZlib_zError
#define zlibVersion            CZlib_zlibVersion
#define zlibCompileFlags       CZlib_zlibCompileFlags

#define z_errmsg               CZlib_z_errmsg

#endif /* CZLIB_RENAME_H */
RENAME

echo "==> Patching zconf.h to include czlib_rename.h..."
cat >> "${CZLIB_DIR}/include/zconf.h" <<'PATCH'

/* --- czlib vendoring: rename public symbols to avoid dylib clash --- */
#include "czlib_rename.h"
PATCH

# ---------------------------------------------------------------------------
# 5. Create modulemap
# ---------------------------------------------------------------------------
echo "==> Creating module.modulemap..."
cat > "${CZLIB_DIR}/include/module.modulemap" <<'MODULEMAP'
module CZlib {
    header "zlib.h"
    export *
}
MODULEMAP

# ---------------------------------------------------------------------------
# 6. Create shim header that includes zlib.h (optional convenience)
# ---------------------------------------------------------------------------
cat > "${CZLIB_DIR}/include/CZlib.h" <<'SHIM'
#ifndef CZLIB_H
#define CZLIB_H

#include "zlib.h"

#endif /* CZLIB_H */
SHIM

# ---------------------------------------------------------------------------
# 7. Record the vendored version
# ---------------------------------------------------------------------------
echo "${ZLIB_VERSION}" > "${CZLIB_DIR}/ZLIB_VERSION"
cp "${ZLIB_SRC}/LICENSE" "${CZLIB_DIR}/LICENSE" 2>/dev/null \
    || cp "${ZLIB_SRC}/README" "${CZLIB_DIR}/README" 2>/dev/null \
    || true

# ---------------------------------------------------------------------------
# 8. Validate symbol prefixes (compile + nm)
# ---------------------------------------------------------------------------
# Compile each .c file and confirm that every public (T) symbol in the
# resulting object carries the CZlib_ prefix.  This catches any functions
# missing from czlib_rename.h before they can cause link-time clashes.
echo "==> Validating symbol prefixes..."
OBJ_DIR="${WORK_DIR}/obj"
mkdir -p "${OBJ_DIR}"
validation_failed=0

for f in "${CZLIB_DIR}/src/"*.c; do
    obj="${OBJ_DIR}/$(basename "${f}").o"
    if ! clang -c \
            -I"${CZLIB_DIR}/include" \
            -I"${CZLIB_DIR}/src" \
            "${f}" -o "${obj}" 2>/dev/null; then
        echo "  WARNING: clang failed to compile $(basename "${f}") — skipping" >&2
        validation_failed=1
        continue
    fi
    bad="$(nm "${obj}" 2>/dev/null | awk '$2 == "T" && $3 !~ /^_CZlib_/ { print $3 }')"
    if [[ -n "${bad}" ]]; then
        echo "  ERROR: $(basename "${f}") has unprefixed public symbols:" >&2
        echo "${bad}" | sed 's/^/    /' >&2
        validation_failed=1
    fi
done

if [[ "${validation_failed}" -ne 0 ]]; then
    echo "" >&2
    echo "Error: unprefixed symbols detected — add them to czlib_rename.h and re-run." >&2
    exit 1
fi
echo "==> Validation passed: all public symbols carry the CZlib_ prefix"

echo ""
echo "==> zlib ${ZLIB_VERSION} vendored successfully into ${CZLIB_DIR}"
